version: "3"

services:

  # influx container with database volume mounted at $PWD/influxdbstore
  influxdbstore:
    image: "influxdb"
    ports:
      - "8081:8086"
    networks:
      - shared
    volumes:
      - "./influxdbstore:/var/lib/influxdb"
    environment:
      - INFLUXDB_DB=metrics

networks:
  shared:
