influxdbDir = ${CURDIR}/influxdbstore
#osfiles = ${CURDIR}/osfiles.tgz

# Run uses docker-compose to spin up influx DB and TBD API locally (this is the default target)
#run: tbd-api htpasswd test-statestore cert.crt
run: docker-compose up --no-build
